version: "2"

services:
  scad:
    build: .
    volumes:
      - ./:/app

    ports:
      - 8000:8000

    command: ["./startup.sh"]
    # depends_on:
    #   - postgres

  # postgres:
  #   image: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - postgres_backup:/backups
  #   environment:
  #     - POSTGRES_USER=metakitex
  #     - POSTGRES_DB=metarkitexdb
  #     - POSTGRES_PASSWORD=password

  #   ports:
  #     - "5432:5432"


# volumes:
#   postgres_data: {}
#   postgres_backup: {}
